name: namer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  google_fonts: ^6.2.1
  # or flutter_riverpod/hooks_riverpod as per https://riverpod.dev/docs/getting_started
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1


dev_dependencies:
  # a tool for running code generators
  build_runner: ^2.5.4
  # the code generator
  riverpod_generator: ^2.6.5
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: ^2.6.5
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: ^0.7.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png